"""removed overlaps, added backpopulates

Revision ID: d3b31210b477
Revises: 375464893bfe
Create Date: 2023-06-27 09:48:01.252110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3b31210b477'
down_revision = '375464893bfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_applications', schema=None) as batch_op:
        batch_op.drop_column('notes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
